name: github pages

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: yarn build and deploy
      run: |
        yarn run build
        yarn deploy
